# Generated by Django 4.1.2 on 2022-11-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_album', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('release_date', models.IntegerField()),
            ],
        ),
    ]
